//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyArgs.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerifyArgs.Util.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be in range [{0},{1}]..
        /// </summary>
        internal static string InRange {
            get {
                return ResourceManager.GetString("InRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be equal {0}..
        /// </summary>
        internal static string LengthEqual {
            get {
                return ResourceManager.GetString("LengthEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be in range [{0},{1}]..
        /// </summary>
        internal static string LengthInRange {
            get {
                return ResourceManager.GetString("LengthInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be less than or equal {0}..
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be less than or equal {0}..
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value length should be greater than or equal {0}..
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater than or equal {0}..
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be negative (less than zero)..
        /// </summary>
        internal static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.Args() argument is expected to be an anonymous object, actual argument is of type &quot;{0}&quot;..
        /// </summary>
        internal static string NotAnonymousType {
            get {
                return ResourceManager.GetString("NotAnonymousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be default..
        /// </summary>
        internal static string NotDefault {
            get {
                return ResourceManager.GetString("NotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be empty..
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be negative (not less than zero)..
        /// </summary>
        internal static string NotNegative {
            get {
                return ResourceManager.GetString("NotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be positive (not greater than zero)..
        /// </summary>
        internal static string NotPositive {
            get {
                return ResourceManager.GetString("NotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be positive (greater than zero)..
        /// </summary>
        internal static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
    }
}
